version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: samokat_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: samokat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Docer/sql/init.sql:/docker-entrypoint-initdb.d/init.sql # Монтирование SQL-скрипта для инициализации
    ports:
      - "5432:5432"
    networks:
      - samokat_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456789
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - samokat_network

volumes:
  postgres_data:

networks:
  samokat_network:
    driver: bridge
